name: Deployment pipeline

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI/CD environment

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build and run tests
        env:
          INTERNAL_SECRET_KEY: ${{ secrets.INTERNAL_SECRET_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          REDIS_CLOUD_HOST: ${{ secrets.REDIS_CLOUD_HOST }}
          REDIS_CLOUD_PASSWORD: ${{ secrets.REDIS_CLOUD_PASSWORD }}
          REDIS_CLOUD_PORT: ${{ secrets.REDIS_CLOUD_PORT }}
          REDIS_CLOUD_USER: ${{ secrets.REDIS_CLOUD_USER }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_SECRET: ${{ secrets.SUPABASE_SECRET }}
          SUPABASE_SECRET_API_KEY: ${{ secrets.SUPABASE_SECRET_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: ./gradlew clean build --no-daemon

      - name: Deploy
        run: echo "Deploying..."

  deploy:
    needs: build
    environment: CI/CD environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh 

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false